### ISSUE TITLE
DJI FPV

### ISSUE THREAD

**Issue by madoboy** [pkurucz/opentelem_to_bst_bridge#1]
Hi. 
Any chance to make Vector telemetry work on DJI FPV system? 
Thanks

**Comment by pkurucz** [comment]
Looks like Daemon in RCGroups is working on a variant that supports the DJI system.  
See here: https://www.rcgroups.com/forums/showpost.php?p=43481809&postcount=9647

Feel free to submit a pull request if you have any changes that you'd like to see incorporated :)
