### ISSUE TITLE
I2C Pull-Up Resistors

### ISSUE THREAD

**Issue by yngndrw** [pkurucz/opentelem_to_bst_bridge#3]
Hello,

I was just wondering why you've switched to external pull-up resistors in your code - I couldn't find any notes about why this has been done and if it's necessary or if it's just an experiment that has been left in:
https://github.com/pkurucz/opentelem_to_bst_bridge/blob/master/bst_telemetry.cpp#L158-L170

Thanks,
-Andrew.

**Comment by pkurucz** [comment]
The internal pull-ups on my 328p were too weak causing the rise time to be
too low even at 100 KHz.  I left it in incase other arduino MCUs have
stronger pull-ups.

~pk

**Comment by yngndrw** [comment]
Thank you, I'll be using the same microcontroller so I'll be sure to use external pull-ups.
